# Generated by Django 3.0.12 on 2021-02-19 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_edit', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=80)),
                ('details', models.TextField()),
                ('category', models.CharField(choices=[('U', 'Urgent'), ('S', 'Soon'), ('E', 'Eventually'), ('A', 'Always')], default='E', max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
