# Generated by Django 3.0.12 on 2021-02-21 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_episodeofcare_patient'),
        ('reflections', '0002_reflection_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='reflection',
            name='episode_of_care',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.EpisodeOfCare'),
        ),
        migrations.AddField(
            model_name='reflection',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Patient'),
        ),
    ]
