# Generated by Django 3.0.12 on 2021-02-24 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_episodeofcare_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reflections', '0004_auto_20210223_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuidedReflection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_edit', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=80)),
                ('question1', models.TextField()),
                ('question2', models.TextField()),
                ('question3', models.TextField()),
                ('category', models.CharField(choices=[('GE', 'General'), ('IM', 'Areas to Improve'), ('SU', 'Success'), ('FA', 'Failue'), ('O', 'Other')], default='GE', max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guided_reflections', to=settings.AUTH_USER_MODEL)),
                ('episode_of_care', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guided_reflections', to='users.EpisodeOfCare')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Patient')),
            ],
        ),
    ]
