# Generated by Django 3.0.12 on 2021-02-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_episodeofcare_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodeofcare',
            name='discharge_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
