# Generated by Django 3.0.12 on 2021-02-22 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210221_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='treating_clinician',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
