# Generated by Django 3.0.12 on 2021-02-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210223_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodeofcare',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Discharged', 'Discharged')], max_length=20, null=True),
        ),
    ]
