# Generated by Django 3.0.12 on 2021-02-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_episodeofcare_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access',
            field=models.BooleanField(default=False),
        ),
    ]
