# Generated by Django 3.0.12 on 2021-03-02 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210302_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodeofcare',
            name='clinician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinician_episodes', to=settings.AUTH_USER_MODEL),
        ),
    ]
